//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Case.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appendixs
    {
        public int id_Appendix { get; set; }
        public int id_Student { get; set; }
        public int Depts { get; set; }
        public int Leaves { get; set; }
        public int Improperleaves { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
