//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Case.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendances
    {
        public int id_Attendance { get; set; }
        public int id_Class { get; set; }
        public int id_Teacher { get; set; }
        public int id_Subject { get; set; }
        public int Attendance { get; set; }
        public int Absent { get; set; }
    
        public virtual Subjects Subjects { get; set; }
    }
}
