//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Case.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studentsubjectmarks
    {
        public int id_Studentsubjectmark { get; set; }
        public int id_Student { get; set; }
        public int id_Marktype { get; set; }
        public int id_Subject { get; set; }
    
        public virtual Marktypes Marktypes { get; set; }
        public virtual Students Students { get; set; }
    }
}
