//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Case.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Students()
        {
            this.Appendixs = new HashSet<Appendixs>();
            this.Studentsubjectmarks = new HashSet<Studentsubjectmarks>();
        }
    
        public int id_Student { get; set; }
        public int id_Class { get; set; }
        public string Lastname { get; set; }
        public string Secondname { get; set; }
        public string Firstname { get; set; }
        public Nullable<int> id_Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> Age { get; set; }
        public int id_Authentication { get; set; }
        public string Note { get; set; }
        public bool ProfileEnded { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appendixs> Appendixs { get; set; }
        public virtual Autherizations Autherizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Studentsubjectmarks> Studentsubjectmarks { get; set; }
    }
}
