//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Case.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teachers()
        {
            this.Academicplans = new HashSet<Academicplans>();
            this.Classes = new HashSet<Classes>();
        }
    
        public int id_teacher { get; set; }
        public string FIO { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Education { get; set; }
        public string Adress { get; set; }
        public string Phone { get; set; }
        public int id_Position { get; set; }
        public int id_Autherization { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Academicplans> Academicplans { get; set; }
        public virtual Autherizations Autherizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Classes> Classes { get; set; }
        public virtual Positions Positions { get; set; }
        public virtual Timetables Timetables { get; set; }
    }
}
