//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Case.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Посещаемость
    {
        public int КодПосещяемости { get; set; }
        public Nullable<int> КодУченик { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<bool> Присутствие { get; set; }
        public Nullable<int> КодПредмет { get; set; }
    
        public virtual Предмет Предмет { get; set; }
        public virtual Ученик Ученик { get; set; }
    }
}
