//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Case.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Рассписание
    {
        public int КодРассписания { get; set; }
        public Nullable<int> КодКласс { get; set; }
        public Nullable<int> КодУчитель { get; set; }
        public string Кабинет { get; set; }
    
        public virtual Класс Класс { get; set; }
        public virtual Учитель Учитель { get; set; }
    }
}
