//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Case.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Успеваемость
    {
        public int КодУспеваемости { get; set; }
        public Nullable<int> КодПредмет { get; set; }
        public Nullable<int> КодСтудент { get; set; }
        public Nullable<int> КодКласс { get; set; }
        public string КомментарийУчителя { get; set; }
        public string Оценка { get; set; }
    
        public virtual Предмет Предмет { get; set; }
        public virtual Ученик Ученик { get; set; }
    }
}
