//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Case.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ученик
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ученик()
        {
            this.Посещаемость = new HashSet<Посещаемость>();
            this.Успеваемость = new HashSet<Успеваемость>();
            this.Чат = new HashSet<Чат>();
        }
    
        public int КодУченика { get; set; }
        public string ФИО { get; set; }
        public Nullable<int> Класс { get; set; }
        public string Адрес { get; set; }
        public Nullable<int> КодАвторизаци { get; set; }
    
        public virtual Авторизация Авторизация { get; set; }
        public virtual Класс Класс1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Посещаемость> Посещаемость { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Успеваемость> Успеваемость { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Чат> Чат { get; set; }
    }
}
