//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Case.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Чат
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Чат()
        {
            this.Сообщения = new HashSet<Сообщения>();
        }
    
        public int КодЧата { get; set; }
        public int КодУченика { get; set; }
        public Nullable<int> КодУчителя { get; set; }
        public string Сообщение { get; set; }
    
        public virtual Ученик Ученик { get; set; }
        public virtual Учитель Учитель { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сообщения> Сообщения { get; set; }
    }
}
